#!/usr/bin/env bash
# transfer a file from client to server

if (($# < 3))
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	# scp [options] source ... target
	scp -i ~/.ssh/"$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi
