#!/usr/bin/env bash
# displays 1-100, Fizz, Buzz, or FizzBuzz in stead of
# numbers divisible by 3, 5, and 15 respectively

i=1
while (( i <= 100 ))
do
    if [ $(( i%15 )) -eq 0 ]
    then
        echo "FizzBuzz";
    elif [ $(( i%5 )) -eq 0 ]
    then
        echo "Buzz";
    elif [ $(( i%3 ))  -eq 0 ]
    then
        echo "Fizz";
    else
        echo $i
    fi
    (( i += 1 ))
done
