#!/usr/bin/env bash
# Displays "Best School" 10 times, while loop

i=0

while (( i < 10 ));
do
    if [[ "$i" -eq 9 ]]
    then
        echo "Hi";
    fi

    echo "Best School";
    (( i += 1 ))
done
