#!/usr/bin/env bash
# displays Best School at all but 4th and 8th loop

((i = 0));
while ((i < 10));
do
	((i++));
	if ((i == 4));
	then
		echo "bad luck";
		continue;
	elif ((i == 8));
	then
		echo "good luck";
		continue;
	else
		echo 'Best School';
	fi;
done;
