#!/usr/bin/env bash
# using if, elif and else inside while

i=0

while (( i < 10 ));
do
    if [[ "$i" -eq 3 ]]
    then
        echo "bad luck";

    elif [[ "$i" -eq 7 ]]
    then
    	echo "good luck";

    else
        echo "Best School";
    fi
    (( i += 1 ))
done
