#!/usr/bin/env bash
# Displays all minutes in 12 hours; nested while loop

hour=0
while (( hour < 13 ));
do
    echo "Hour:" $hour
    minute=1;
    while(( minute < 60 ));
    do
        echo "$minute";
        (( minute += 1 ))
    done
    (( hour += 1 ))
done
