#!/usr/bin/env bash
# gives info about the file 'school'
s="school"
if [ -e "$s" ] # check if file exists
then
    echo "school file exists"
    if [ -s "$s" ] # check if empty | size 0
    then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi
    if [ -f "$s" ] # check if it's a regular file
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
