#!/usr/bin/env bash
# configure server to resolve a.) localhost to 127.0.0.1,  b.) facebook.com to 8.8.8.8

# create new hosts file outside of /ect/
cp /etc/hosts hosts.new

echo "127.0.0.2	localhost" > hosts.new
echo "8.8.8.8 	facebook.com" >> hosts.new

sudo cp -f hosts.new /etc/hosts
