#!/usr/bin/env bash
# configures an ubuntu server

# make a copy of the hosts file for recovery
cp /etc/hosts hosts.alx

# link a different ip to localhost and Facebook
echo "127.0.0.2	localhost" > hosts.alx
echo "8.8.8.8	facebook.com" >> hosts.alx

sudo cat /etc/hosts
# copy the 2 lines into original hosts file
sudo cp --force hosts.alx /etc/hosts
