#!/usr/bin/env bash
# uses ssh to connect to your server verbose, don't ask for authentification
ssh -v -o PasswordAuthentication=no -o PreferredAuthentications=publickey -i ~/.ssh/school ubuntu@3.236.21.207
